In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
path = ("D:/Dataset/multi_var_home.xlsx")

In [3]:
df = pd.read_excel(path)

In [4]:
df

area  bedroom  age  price
0   300        1    3     17
1   320        1    2     19
2   370        2    5     17
3   420        2    1     23
4   460        1    2     21
5   500        2    4     24
6   520        3    5     25
7   570        2    3     25
8   610        3    2     27
9   640        3    5     26

In [5]:
df.head()

area  bedroom  age  price
0   300        1    3     17
1   320        1    2     19
2   370        2    5     17
3   420        2    1     23
4   460        1    2     21

In [6]:
df.tail()

area  bedroom  age  price
5   500        2    4     24
6   520        3    5     25
7   570        2    3     25
8   610        3    2     27
9   640        3    5     26

In [7]:
x = df.drop("price",axis=1)
x

area  bedroom  age
0   300        1    3
1   320        1    2
2   370        2    5
3   420        2    1
4   460        1    2
5   500        2    4
6   520        3    5
7   570        2    3
8   610        3    2
9   640        3    5

In [8]:
y = df.drop(["area","bedroom","age"],axis=1)

In [9]:
y

price
0     17
1     19
2     17
3     23
4     21
5     24
6     25
7     25
8     27
9     26

In [10]:
from sklearn.linear_model import LinearRegression

In [11]:
model = LinearRegression()

In [12]:
model.fit(x,y)

LinearRegression()

In [13]:
model.predict([[400,2,4]])

C:\Users\HP\Documents\Python10\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[20.15904229]])

In [14]:
model.intercept_

array([10.78965996])

In [15]:
model.coef_

array([[ 0.02361682,  1.37173611, -0.70520441]])